networks:
  datahub_network:
    external: true
    name: datahub_network
services:
  broker-clima:
    depends_on:
      zookeeper-clima:
        condition: service_healthy
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper-clima:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker-clima:29092,PLAINTEXT_HOST://localhost:9092
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    - KAFKA_HEAP_OPTS=-Xms256m -Xmx256m
    - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    - KAFKA_MESSAGE_MAX_BYTES=5242880
    - KAFKA_MAX_MESSAGE_BYTES=5242880
    healthcheck:
      interval: 1s
      retries: 5
      start_period: 60s
      test: nc -z broker-clima $${DATAHUB_KAFKA_BROKER_PORT:-9092}
      timeout: 5s
    hostname: broker-clima
    image: ${DATAHUB_CONFLUENT_KAFKA_IMAGE:-confluentinc/cp-kafka}:${DATAHUB_CONFLUENT_VERSION:-7.4.0}
    ports:
    - ${DATAHUB_MAPPED_KAFKA_BROKER_PORT:-9093}:9092
    volumes:
    - broker-clima:/var/lib/kafka/data/
    networks:
      - datahub_network
  datahub-actions-clima:
    depends_on:
      datahub-gms-clima:
        condition: service_healthy
    environment:
    - ACTIONS_CONFIG=${ACTIONS_CONFIG:-}
    - ACTIONS_EXTRA_PACKAGES=${ACTIONS_EXTRA_PACKAGES:-}
    - DATAHUB_GMS_HOST=datahub-gms-clima
    - DATAHUB_GMS_PORT=8080
    - DATAHUB_GMS_PROTOCOL=http
    - DATAHUB_SYSTEM_CLIENT_ID=__datahub_system
    - DATAHUB_SYSTEM_CLIENT_SECRET=JohnSnowKnowsNothing
    - KAFKA_BOOTSTRAP_SERVER=broker-clima:29092
    - KAFKA_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
    - METADATA_AUDIT_EVENT_NAME=MetadataAuditEvent_v4
    - METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME=MetadataChangeLog_Versioned_v1
    - SCHEMA_REGISTRY_URL=http://schema-registry-clima:8081
    hostname: actions-clima
    image: ${DATAHUB_ACTIONS_IMAGE:-acryldata/datahub-actions}:${ACTIONS_VERSION:-head}
    volumes:
      - ../../scripts:/datahub/scripts
    # command: >
    #   bash -c "pip install -U acryl-datahub[datahub-rest] && 
    #            python3 /datahub/scripts/clima_to_datahub_container.py"
    command: >
      bash -c "pip install -U acryl-datahub[datahub-rest] && 
      python3 /datahub/scripts/create_domain_clima.py &&
      python3 /datahub/scripts/create_terms_clima.py &&
      python3 /datahub/scripts/create_tags_clima.py"  
    restart: on-failure
    networks:
      - datahub_network
  datahub-frontend-react-clima:
    depends_on:
      datahub-gms-clima:
        condition: service_healthy
    environment:
    - DATAHUB_GMS_HOST=datahub-gms-clima
    - DATAHUB_GMS_PORT=8080
    - DATAHUB_SECRET=YouKnowNothing
    - DATAHUB_APP_VERSION=1.0
    - DATAHUB_PLAY_MEM_BUFFER_SIZE=10MB
    - JAVA_OPTS=-Xms512m -Xmx512m -Dhttp.port=9003 -Dconfig.file=datahub-frontend/conf/application.conf -Djava.security.auth.login.config=datahub-frontend/conf/jaas.conf -Dlogback.configurationFile=datahub-frontend/conf/logback.xml -Dlogback.debug=false -Dpidfile.path=/dev/null
    - KAFKA_BOOTSTRAP_SERVER=broker-clima:29092
    - DATAHUB_TRACKING_TOPIC=DataHubUsageEvent_v1
    - ELASTIC_CLIENT_HOST=elasticsearch-clima
    - ELASTIC_CLIENT_PORT=9200
    - AUTH_OIDC_ENABLED=true
    - AUTH_OIDC_CLIENT_ID=datahub
    - AUTH_OIDC_CLIENT_SECRET=8a665e67-fc6e-490f-a6e2-a96e88ab245d
    - AUTH_OIDC_DISCOVERY_URI=http://192.168.64.14:8585/auth/realms/master/.well-known/openid-configuration
    - AUTH_OIDC_BASE_URL=http://localhost:9003
    - AUTH_SESSION_TTL_HOURS=1
    - MAX_SESSION_TOKEN_AGE=1h
    - AUTH_OIDC_USER_NAME_CLAIM=email
    - AUTH_OIDC_USER_NAME_CLAIM_REGEX=^clima@clima\.com$$
    hostname: datahub-frontend-react-clima
    image: ${DATAHUB_FRONTEND_IMAGE:-acryldata/datahub-frontend-react}:${DATAHUB_VERSION:-head}
    ports:
    - ${DATAHUB_MAPPED_FRONTEND_PORT:-9003}:9002
    volumes:
    - ${HOME}/.datahub/plugins:/etc/datahub/plugins
    networks:
      - datahub_network
  datahub-gms-clima:
    depends_on:
      datahub-upgrade-clima:
        condition: service_completed_successfully
    environment:
    - DATAHUB_SERVER_TYPE=${DATAHUB_SERVER_TYPE:-quickstart}
    - DATAHUB_TELEMETRY_ENABLED=${DATAHUB_TELEMETRY_ENABLED:-true}
    - DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID=generic-duhe-consumer-job-client-gms
    - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
    - EBEAN_DATASOURCE_HOST=mysql-clima:3306
    - EBEAN_DATASOURCE_PASSWORD=datahub
    - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql-clima:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2
    - EBEAN_DATASOURCE_USERNAME=datahub
    - ELASTICSEARCH_HOST=elasticsearch-clima
    - ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
    - ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
    - ELASTICSEARCH_PORT=9200
    - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
    - ENTITY_SERVICE_ENABLE_RETENTION=true
    - ES_BULK_REFRESH_POLICY=WAIT_UNTIL
    - GRAPH_SERVICE_DIFF_MODE_ENABLED=true
    - GRAPH_SERVICE_IMPL=${GRAPH_SERVICE_IMPL:-elasticsearch}
    - JAVA_OPTS=-Xms1g -Xmx1g
    - KAFKA_BOOTSTRAP_SERVER=broker-clima:29092
    - KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR=${KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR:-true}
    - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry-clima:8081
    - MAE_CONSUMER_ENABLED=true
    - MCE_CONSUMER_ENABLED=true
    - METADATA_SERVICE_AUTH_ENABLED=${METADATA_SERVICE_AUTH_ENABLED:-true}
    - NEO4J_HOST=http://neo4j-clima:7474
    - NEO4J_PASSWORD=datahub
    - NEO4J_URI=bolt://neo4j
    - NEO4J_USERNAME=neo4j-clima
    - PE_CONSUMER_ENABLED=true
    - THEME_V2_DEFAULT=true
    - UI_INGESTION_ENABLED=true
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 90s
      test: curl -sS --fail http://datahub-gms-clima:${DATAHUB_GMS_PORT:-8080}/health
      timeout: 5s
    hostname: datahub-gms-clima
    image: ${DATAHUB_GMS_IMAGE:-acryldata/datahub-gms}:${DATAHUB_VERSION:-head}
    ports:
    - ${DATAHUB_MAPPED_GMS_PORT:-8082}:8080
    volumes:
    - ${HOME}/.datahub/plugins:/etc/datahub/plugins
    networks:
      - datahub_network
  datahub-upgrade-clima:
    build:
        context: ../../
        dockerfile: datahub-quickstart/datahub-upgrade/Dockerfile
    command:
    - -u
    - SystemUpdate
    depends_on:
      elasticsearch-setup-clima:
        condition: service_completed_successfully
      kafka-setup-clima:
        condition: service_completed_successfully
      mysql-setup-clima:
        condition: service_completed_successfully
      # neo4j-clima:
      #   condition: service_healthy
    environment:
    - BACKFILL_BROWSE_PATHS_V2=true
    - DATAHUB_GMS_HOST=datahub-gms-clima
    - DATAHUB_GMS_PORT=8080
    - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
    - EBEAN_DATASOURCE_HOST=mysql-clima:3306
    - EBEAN_DATASOURCE_PASSWORD=datahub
    - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql-clima:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
    - EBEAN_DATASOURCE_USERNAME=datahub
    - ELASTICSEARCH_BUILD_INDICES_CLONE_INDICES=false
    - ELASTICSEARCH_HOST=elasticsearch-clima
    - ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
    - ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
    - ELASTICSEARCH_PORT=9200
    - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
    - GRAPH_SERVICE_IMPL=${GRAPH_SERVICE_IMPL:-elasticsearch}
    - KAFKA_BOOTSTRAP_SERVER=broker-clima:29092
    - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry-clima:8081
    - REPROCESS_DEFAULT_BROWSE_PATHS_V2=false
    hostname: datahub-upgrade-clima
    image: ${DATAHUB_UPGRADE_IMAGE:-acryldata/datahub-upgrade}:${DATAHUB_VERSION:-head}
    labels:
      datahub_setup_job: true
    networks:
      - datahub_network
  elasticsearch-clima:
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
    - discovery.type=single-node
    - ${XPACK_SECURITY_ENABLED:-xpack.security.enabled=false}
    - ES_JAVA_OPTS=-Xms256m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
    - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 20s
      test: curl -sS --fail http://elasticsearch-clima:$${DATAHUB_ELASTIC_PORT:-9200}/_cluster/health?wait_for_status=yellow&timeout=0s
      timeout: 5s
    hostname: elasticsearch-clima
    image: ${DATAHUB_SEARCH_IMAGE:-elasticsearch}:${DATAHUB_SEARCH_TAG:-7.10.1}
    ports:
    - ${DATAHUB_MAPPED_ELASTIC_PORT:-9201}:9200
    volumes:
    - esdata-clima:/usr/share/elasticsearch/data
    networks:
      - datahub_network
  elasticsearch-setup-clima:
    depends_on:
      elasticsearch-clima:
        condition: service_healthy
    environment:
    - ELASTICSEARCH_USE_SSL=${ELASTICSEARCH_USE_SSL:-false}
    - USE_AWS_ELASTICSEARCH=${USE_AWS_ELASTICSEARCH:-false}
    - ELASTICSEARCH_HOST=elasticsearch-clima
    - ELASTICSEARCH_PORT=9200
    - ELASTICSEARCH_PROTOCOL=http
    hostname: elasticsearch-setup-clima
    image: ${DATAHUB_ELASTIC_SETUP_IMAGE:-acryldata/datahub-elasticsearch-setup}:${DATAHUB_VERSION:-head}
    labels:
      datahub_setup_job: true
    networks:
      - datahub_network
  kafka-setup-clima:
    depends_on:
      broker-clima:
        condition: service_healthy
      schema-registry-clima:
        condition: service_healthy
    environment:
    - DATAHUB_PRECREATE_TOPICS=${DATAHUB_PRECREATE_TOPICS:-false}
    - KAFKA_BOOTSTRAP_SERVER=broker-clima:29092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper-clima:2181
    - USE_CONFLUENT_SCHEMA_REGISTRY=TRUE
    hostname: kafka-setup-clima
    image: ${DATAHUB_KAFKA_SETUP_IMAGE:-acryldata/datahub-kafka-setup}:${DATAHUB_VERSION:-head}
    labels:
      datahub_setup_job: true
    networks:
      - datahub_network
  mysql-clima:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_DATABASE=datahub
    - MYSQL_USER=datahub
    - MYSQL_PASSWORD=datahub
    - MYSQL_ROOT_PASSWORD=datahub
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 10s
      # test: mysqladmin ping -h mysql -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "datahub", "-pdatahub"]
      timeout: 5s
    hostname: mysql-clima
    image: mysql:${DATAHUB_MYSQL_VERSION:-8.2}
    ports:
    - ${DATAHUB_MAPPED_MYSQL_PORT:-3307}:3306
    restart: on-failure
    volumes:
    - mydb-clima:/var/lib/mysql
    networks:
      - datahub_network
  mysql-setup-clima:
    depends_on:
      mysql-clima:
        condition: service_healthy
    environment:
    - MYSQL_HOST=mysql-clima
    - MYSQL_PORT=3306
    - MYSQL_USERNAME=datahub
    - MYSQL_PASSWORD=datahub
    - DATAHUB_DB_NAME=datahub
    hostname: mysql-setup-clima
    image: ${DATAHUB_MYSQL_SETUP_IMAGE:-acryldata/datahub-mysql-setup}:${DATAHUB_VERSION:-head}
    labels:
      datahub_setup_job: true
    networks:
      - datahub_network
  neo4j-clima:
    environment:
    - NEO4J_AUTH=neo4j/datahub
    - NEO4J_dbms_default__database=graph.db
    - NEO4J_dbms_allow__upgrade=true
    - NEO4JLABS_PLUGINS=["apoc"]
    healthcheck:
      interval: 1s
      retries: 5
      start_period: 5s
      test: wget http://neo4j-clima:$${DATAHUB_NEO4J_HTTP_PORT:-7474}
      timeout: 5s
    hostname: neo4j-clima
    image: neo4j:4.4.9-community
    ports:
    - ${DATAHUB_MAPPED_NEO4J_HTTP_PORT:-7475}:7474
    - ${DATAHUB_MAPPED_NEO4J_BOLT_PORT:-7688}:7687
    volumes:
    - neo4jdata-clima:/data
    networks:
      - datahub_network
  schema-registry-clima:
    depends_on:
      broker-clima:
        condition: service_healthy
    environment:
    - SCHEMA_REGISTRY_HOST_NAME=schemaregistry-clima
    - SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=PLAINTEXT
    - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=broker-clima:29092
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 60s
      test: nc -z schema-registry-clima ${DATAHUB_SCHEMA_REGISTRY_PORT:-8081}
      timeout: 5s
    hostname: schema-registry-clima
    image: ${DATAHUB_CONFLUENT_SCHEMA_REGISTRY_IMAGE:-confluentinc/cp-schema-registry}:${DATAHUB_CONFLUENT_VERSION:-7.4.0}
    ports:
    - ${DATAHUB_MAPPED_SCHEMA_REGISTRY_PORT:-8083}:8081
    networks:
      - datahub_network
  zookeeper-clima:
    environment:
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
    healthcheck:
      interval: 5s
      retries: 3
      start_period: 10s
      test: echo srvr | nc zookeeper-clima $${DATAHUB_ZK_PORT:-2181}
      timeout: 5s
    hostname: zookeeper-clima
    image: ${DATAHUB_CONFLUENT_ZOOKEEPER_IMAGE:-confluentinc/cp-zookeeper}:${DATAHUB_CONFLUENT_VERSION:-7.4.0}
    ports:
    - ${DATAHUB_MAPPED_ZK_PORT:-2182}:2181
    volumes:
    - zkdata-clima:/var/lib/zookeeper/data
    - zklogs-clima:/var/lib/zookeeper/log
    networks:
      - datahub_network
  
volumes:
  broker-clima: null
  esdata-clima: null
  mydb-clima: null
  neo4jdata-clima: null
  zkdata-clima: null
  zklogs-clima: null
