version: "3.5"
services:
  mongo-clima:
    image: mongo:${MONGO_VERSION}
    container_name: mongo_datahub_clima
    command: --nojournal
    ports:
    - "21018:27017"
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`; 
        mongo-clima --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
    volumes: 
      - mongo-db-data-clima:/data/db 
    networks:
      - datahub_network
    restart: unless-stopped

  orion-clima:
    image: fiware/orion-ld:${ORION_VERSION}
    container_name: orion_datahub_clima
    depends_on:
      - mongo-clima
    command: -dbhost mongo-clima -lmtmp -logLevel WARN
    ports:
    - "1027:1026"
    expose:
      - 1026
      - 1027
    environment:
      ORIONLD_MONGO_USER: ${MONGO_ROOT_USERNAME}
      ORIONLD_MONGO_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - datahub_network
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://orion-clima:1026/version || exit 1



  draco-clima:
    #image: ging/fiware-draco:${DRACO_VERSION}
    build:
      context: ./draco
      args:
        DRACO_VERSION: ${DRACO_VERSION}
      target: ${TARGET} 
    container_name: draco_datahub_clima
    environment:
      NIFI_WEB_HTTPS_PORT: 9091
      NIFI_WEB_HTTPS_HOST: 0.0.0.0
      NIFI_WEB_PROXY_HOST: ${IP_SERVER}:9091
      SINGLE_USER_CREDENTIALS_USERNAME: ${DRACO_USERNAME}
      SINGLE_USER_CREDENTIALS_PASSWORD: ${DRACO_PASSWORD}
    ports:
      - "9091:9091"
      - "5060-5069:5050-5059"
    networks:
      - datahub_network
    volumes: 
      - ./draco/templates:/opt/nifi/nifi-current/conf/templates
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s -k https://draco-clima:9091/nifi-api/system-diagnostics || exit 1
      start_period: 1m

volumes: 
  mongo-db-data-clima:

networks:
  datahub_network:
    external: true
    name: datahub_network
