version: '3.5'
services:
  proxy:
    image: nginx:1.21
    container_name: proxy_datahub
    ports:
      - 80:80
      - 443:443
      - 1024:1024
    volumes:
      - ./configs/:/etc/nginx/conf.d/:ro
      - ./public/:/usr/share/nginx/html/:ro
      - ./ssl/:/etc/nginx/ssl/:ro
    networks:
      - datahub_network
    restart: unless-stopped

networks:
  datahub_network:
    external: true
    name: datahub_network
